In [2]:
import numpy as np

a = np.array([1, 2, 3])           
b = np.array([[1, 2], [3, 4]])    
z = np.zeros((2, 3))              
o = np.ones((3, 3))               
r = np.arange(0, 10, 2)           
l = np.linspace(0, 1, 5)

In [3]:
print(a.shape)
print(a.ndim)
print(a.dtype)


(3,)
1
int64


In [4]:
print(b[0,1])
print(r[1:4])

2
[2 4 6]


In [6]:
print(a + 5)       
print(a * 2)       
print(a + b[0,1])    
print(np.dot(b, b))


[6 7 8]
[2 4 6]
[3 4 5]
[[ 7 10]
 [15 22]]


In [7]:
print(np.sum(a))   
print(np.mean(a))  
print(np.max(a))   
print(np.sqrt(a))  

6
2.0
3
[1.         1.41421356 1.73205081]


In [8]:
x = np.arange(6).reshape(2, 3)   
print(x.T)

[[0 3]
 [1 4]
 [2 5]]


In [9]:
rand_arr = np.random.rand(2, 3)
rand_int = np.random.randint(1, 10, 5)  

In [10]:
np.save('array_file.npy', a)
loaded = np.load('array_file.npy')

In [11]:
m = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(m))
print(np.linalg.det(m))

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [12]:
arr = np.array([1, 3, 2, 3])
print(np.unique(arr))
print(np.sort(arr))
print(np.where(arr > 2))          

[1 2 3]
[1 2 3 3]
(array([1, 3]),)
