In [17]:
import numpy as np

In [18]:
a = [10,20,30,40]

In [19]:
type(a)

list

In [20]:
x = np.array(a)

In [21]:
print(x)

[10 20 30 40]


In [22]:
type(x)

numpy.ndarray

In [23]:
a = [1,2,3,4]
b = [10,20,30,40]
x = np.array([a,b])

In [24]:
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [25]:
a = [1,2,3,4]
b = [10,20,30,40]
x = np.array([a,b])

In [26]:
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [27]:
x = np.array([1,2,3,4], dtype = np.float32)
print(x)

[1. 2. 3. 4.]


In [28]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [29]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [32]:
x = np.random.rand(2,5)

In [33]:
print(x)

[[0.9771561  0.31418418 0.24399349 0.82751514 0.00916131]
 [0.9291844  0.2954866  0.20917828 0.46478677 0.1995148 ]]


In [122]:
np.random.rand

<bound method RandomState.rand of RandomState(MT19937) at 0x1A6D0315B40>

In [35]:
np.random.randint(1,20, size = (3,3))

array([[13, 10, 16],
       [ 6, 18,  3],
       [11, 15, 11]], dtype=int32)

In [123]:
np.random.randint

<bound method RandomState.randint of RandomState(MT19937) at 0x1A6D0315B40>

In [37]:
np.random.randn(2,5)

array([[ 0.36320984,  0.78491325,  0.57615872,  0.075364  , -0.11903791],
       [ 0.10845958, -0.2441943 , -0.99583906,  1.10011719, -0.45069616]])

In [124]:
np.random.randn

<bound method RandomState.randn of RandomState(MT19937) at 0x1A6D0315B40>

In [39]:
np.random.choice([2,3,4,7,8,10])

np.int64(3)

In [40]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [41]:
np.ones((3,3))*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [42]:
x = np.eye(4, k = -1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [125]:
np.eye

<function numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)>

In [44]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [45]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [46]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [47]:
a = [10,20,30,40,50]
x = np.array(a)
print(x)

[10 20 30 40 50]


In [48]:
x.ndim

1

In [49]:
b = [1,2,3,4,5]
y = np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [50]:
y.ndim

2

In [51]:
y.shape

(2, 5)

In [52]:
y.size

10

In [53]:
a = np.array([3,6,9,12])
print(a)

[ 3  6  9 12]


In [54]:
np.reshape(a, (2,2))

array([[ 3,  6],
       [ 9, 12]])

In [55]:
a.reshape(2,2)

array([[ 3,  6],
       [ 9, 12]])

In [56]:
x = np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
x.size

15

In [58]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [59]:
x = np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [60]:
y = x.reshape(3,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [61]:
z = np.transpose(y)
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [62]:
y.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [63]:
a = np.arange(1,10)

In [64]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [65]:
a[2:6]

array([3, 4, 5, 6])

In [66]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
x[1,2]

np.int64(6)

In [68]:
x[1][2]

np.int64(6)

In [69]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [70]:
a = np.arange(1,6)
b = np.arange(6,11)

In [71]:
print(a)

[1 2 3 4 5]


In [72]:
print(b)

[ 6  7  8  9 10]


In [73]:
x = np.vstack((a,b))

In [74]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [75]:
x = np.hstack((a,b))

In [76]:
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [77]:
a = np.arange(1,10).reshape(3,3)

In [78]:
b = np.arange(10,19).reshape(3,3)

In [79]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [80]:
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [81]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [82]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [83]:
a = np.arange(10,21,2)

In [84]:
b = np.array([[2],[2]])

In [85]:
print(a)

[10 12 14 16 18 20]


In [86]:
print(b)

[[2]
 [2]]


In [87]:
z = a+b
print(z)

[[12 14 16 18 20 22]
 [12 14 16 18 20 22]]


In [88]:
a = np.arange(10,21,2)

In [89]:
a+2

array([12, 14, 16, 18, 20, 22])

In [90]:
a - b

array([[ 8, 10, 12, 14, 16, 18],
       [ 8, 10, 12, 14, 16, 18]])

In [91]:
a*b

array([[20, 24, 28, 32, 36, 40],
       [20, 24, 28, 32, 36, 40]])

In [92]:
a = np.ones((3,3))
b = np.array([2])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [93]:
print(b)

[2]


In [94]:
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [95]:
a-b

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [96]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [97]:
print(a+5)

[[6. 5. 5. 5.]
 [5. 6. 5. 5.]
 [5. 5. 6. 5.]
 [5. 5. 5. 6.]]


In [98]:
a - 1

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [99]:
a*2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [100]:
a/0.5

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [101]:
np.sin(a)

array([[0.84147098, 0.        , 0.        , 0.        ],
       [0.        , 0.84147098, 0.        , 0.        ],
       [0.        , 0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.        , 0.84147098]])

In [102]:
np.cos(a)

array([[0.54030231, 1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 0.54030231]])

In [103]:
np.sqrt(a)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [104]:
a = np.arange(5,15,2)

In [105]:
print(a)

[ 5  7  9 11 13]


In [106]:
np.mean(a)

np.float64(9.0)

In [107]:
np.median(a)

np.float64(9.0)

In [108]:
np.std(a)

np.float64(2.8284271247461903)

In [109]:
a = np.array([[1,6],[4,3]])
print(a)

[[1 6]
 [4 3]]


In [110]:
print(np.min(a, axis = 0))

[1 3]


In [111]:
print(np.min(a, axis = 1))

[1 3]


In [112]:
print(np.max(a, axis = 1))

[6 4]


In [113]:
print(np.max(a, axis = 0))

[4 6]


In [114]:
a = np.array([1,4,3,10,20])

In [115]:
x = np.sort(a, kind = 'mergesort')

In [116]:
print(x)

[ 1  3  4 10 20]


In [117]:
A = np.arange(0,9).reshape(3,3)
B = np.ones((3,3))

In [118]:
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [119]:
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [120]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [121]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])